 # 1.Understanding the Business Problem

In [1]:
## Import Libraries ##

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

## 1.1  Loading the Dataset

In [2]:
df=pd.read_csv(r"C:\Users\SHAIK RASHEED\Downloads\loan_data.csv")

In [3]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y
377,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
378,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
379,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
380,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

# 2.Understanding the Data

In [4]:
df.head()                                               ##  Displays the Top 5 Rows ##

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [5]:
df.tail()                                                               ##  Displays the Bottom 5 Rows ##

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
376,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y
377,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
378,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
379,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
380,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [6]:
df.shape

(381, 13)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            381 non-null    object
 1   Gender             376 non-null    object
 2   Married            381 non-null    object
 3   Dependents         373 non-null    object
 4   Education          381 non-null    object
 5   Self_Employed      360 non-null    object
 6   ApplicantIncome    381 non-null    int64
 7   CoapplicantIncome  381 non-null    float64
 8   LoanAmount         381 non-null    float64
 9   Loan_Amount_Term   370 non-null    float64
 10  Credit_History     351 non-null    float64
 11  Property_Area      381 non-null    object
 12  Loan_Status        381 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 38.8+ KB

# 3. Data Cleaning

In [8]:
df.isnull().sum()                                          ## Detecting the missing  values ##

Loan_ID               0
Gender                5
Married               0
Dependents            8
Education             0
Self_Employed        21
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [9]:
## Numerical columns were filled using MEAN  or MEDIAN ##
## Categorical columns were filled with MODE ##
df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)                 
df["Dependents"].fillna(df["Dependents"].mode()[0], inplace=True)
df["Self_Employed"].fillna(df["Self_Employed"].mode()[0], inplace=True)
df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].median(), inplace=True)
df["Credit_History"].fillna(df["Credit_History"].mode()[0], inplace=True)

In [10]:
df.isnull().sum()                            ## Again I Detect the missing values

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# 4.Exploratory Data Analysis

In [11]:
df["Gender"].value_counts()

Gender
Male      296
Female     85
Name: count, dtype: int64

In [12]:
df["Education"].value_counts()

Education
Graduate        278
Not Graduate    103
Name: count, dtype: int64

In [13]:
df["Loan_Status"].value_counts()

Loan_Status
Y    271
N    110
Name: count, dtype: int64

In [14]:
df.groupby("Loan_Status")["ApplicantIncome"].mean()

Loan_Status
N    3602.472727
Y    3570.660517
Name: ApplicantIncome, dtype: float64

## 4.1 Feature Engineering

In [15]:
df["Total_Income"]=df["ApplicantIncome"]+df["CoapplicantIncome"]

In [16]:
df[["ApplicantIncome","CoapplicantIncome","Total_Income"]].head()

   ApplicantIncome  CoapplicantIncome  Total_Income
0             4583             1508.0        6091.0
1             3000                0.0        3000.0
2             2583             2358.0        4941.0
3             6000                0.0        6000.0
4             2333             1516.0        3849.0

In [17]:
df.groupby("Loan_Status")["Total_Income"].mean()

Loan_Status
N    4846.663636
Y    4861.365018
Name: Total_Income, dtype: float64

In [18]:
df.groupby("Property_Area")["Loan_Status"].value_counts()

Property_Area  Loan_Status
Rural          Y               65
               N               41
Semiurban      Y              119
               N               30
Urban          Y               87
               N               39
Name: count, dtype: int64

In [19]:
df.groupby("Education")["Loan_Status"].value_counts()

Education     Loan_Status
Graduate      Y              202
              N               76
Not Graduate  Y               69
              N               34
Name: count, dtype: int64

In [20]:
df.to_csv("clean_Finance_loan_data.csv",index=False)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,6091.0
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,3000.0
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,4941.0
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,6000.0
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y,3849.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y,5703.0
377,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y,5182.0
378,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,2900.0
379,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,4106.0
380,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,4583.0

In [21]:
df.shape

(381, 14)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            381 non-null    object
 1   Gender             381 non-null    object
 2   Married            381 non-null    object
 3   Dependents         381 non-null    object
 4   Education          381 non-null    object
 5   Self_Employed      381 non-null    object
 6   ApplicantIncome    381 non-null    int64
 7   CoapplicantIncome  381 non-null    float64
 8   LoanAmount         381 non-null    float64
 9   Loan_Amount_Term   381 non-null    float64
 10  Credit_History     381 non-null    float64
 11  Property_Area      381 non-null    object
 12  Loan_Status        381 non-null    object
 13  Total_Income       381 non-null    float64
dtypes: float64(5), int64(1), object(8)
memory usage: 41.8+ KB

In [23]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
Total_Income         0
dtype: int64

In [24]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
Total_Income         float64
dtype: object

In [25]:
df=df.drop_duplicates()                                                ##  Remove duplicates  ##

In [26]:
df["Approval_Flag"]=df["Loan_Status"].map({"Y":1, "N":0})             ##  create new column "Approval_Flag"  ##

In [27]:
df["Loan by Credit"]=df["Credit_History"].fillna(0).apply(lambda x: "Approved" if x==1 else "Rejected")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income,Approval_Flag,Loan by Credit
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,6091.0,0,Approved
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,3000.0,1,Approved
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,4941.0,1,Approved
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,6000.0,1,Approved
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y,3849.0,1,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y,5703.0,1,Approved
377,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y,5182.0,1,Approved
378,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,2900.0,1,Approved
379,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,4106.0,1,Approved
380,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,4583.0,0,Rejected

In [28]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Total_Income,Approval_Flag
count,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000
mean,3579.845144,1277.275381,104.986877,341.417323,0.850394,4857.120525,0.711286
std,1419.813818,2340.818114,28.358464,67.625957,0.357154,2417.069533,0.453761
min,150.000000,0.000000,9.000000,12.000000,0.000000,1442.000000,0.000000
25%,2600.000000,0.000000,90.000000,360.000000,1.000000,3664.000000,0.000000
50%,3333.000000,983.000000,110.000000,360.000000,1.000000,4600.000000,1.000000
75%,4288.000000,2016.000000,127.000000,360.000000,1.000000,5500.000000,1.000000
max,9703.000000,33837.000000,150.000000,480.000000,1.000000,35673.000000,1.000000

In [29]:
df.to_csv("Final_cleaning_loan_data.csv", index=False)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income,Approval_Flag,Loan by Credit
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,6091.0,0,Approved
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,3000.0,1,Approved
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,4941.0,1,Approved
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,6000.0,1,Approved
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y,3849.0,1,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y,5703.0,1,Approved
377,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y,5182.0,1,Approved
378,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,2900.0,1,Approved
379,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,4106.0,1,Approved
380,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,4583.0,0,Rejected

### conclusion :
                This project Highlights how education and income significantly influence loan Approvals, with higher demand in Urban regions. The end-to-end analysis using python ,SQL, and Power BI Provides actionable insightsto support data-driven loan decisions.